block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('static', 'static'),
        ('data', 'data'),
        ('cobaltstrikec2', 'cobaltstrikec2'),
        ('hunt_1.resource', '.'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'uvicorn.main',
        'fastapi',
        'fastapi.staticfiles',
        'fastapi.responses',
        'pydantic',
        'pydantic.deprecated.class_validators',
        'httpx',
        'anyio',
        'anyio._backends._asyncio',
        'starlette.routing',
        'starlette.staticfiles',
        'robot',
        'robot.libraries.BuiltIn',
        'robot.libraries.Collections',
        'robot.libraries.String',
        'robot.libraries.OperatingSystem',
        'robot.libraries.Process',
        'robot.libraries.DateTime',
        'SSHLibrary',
        'SCPLibrary',
        'paramiko',
        'invoke',
        'websockets',
        'websockets.legacy',
        'websockets.legacy.server',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'numpy'],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='lumen',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    name='lumen',
)
