"""
robot_script_builder.py
------------------------
Helpers used by Lumen's campaign-to-Robot-script compiler to ensure that
the cobaltstrike RF library is imported with the correct constructor
arguments so CS credentials flow into every keyword execution.

Gap 2 root cause
~~~~~~~~~~~~~~~~
Robot Framework calls ``cobaltstrike()`` with NO arguments when it imports
the library.  The constructor sets LOCAL_BIND_IP="", CS_PASSWORD="", etc.
Keywords then call ``_configure_and_validate()`` which can auto-detect the
local IP, but it cannot guess the teamserver password or CS_DIR.

Fix
~~~
The generated ``.robot`` file must declare the library like this::

    Library    cobaltstrikec2/cobaltstrike.py
    ...    WITH NAME    cs
    ...    local_bind_ip=${CS_IP}
    ...    user=${CS_USER}
    ...    cs_password=${CS_PASS}
    ...    cs_dir=${CS_DIR}
    ...    port=${CS_PORT}
    ...    debug=${DEBUG_MODE}

``build_library_declaration()`` produces that exact block given a dict of
global settings from the Lumen UI.

``build_robot_header()`` produces the full ``*** Settings ***`` section
(library + any resource imports) ready to prepend to a generated test suite.
"""

from __future__ import annotations
from typing import Dict, List, Optional


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_LIBRARY_PATH = "cobaltstrikec2/cobaltstrike.py"
_LIBRARY_ALIAS = "cs"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_library_declaration(
    cs_ip: str,
    cs_user: str,
    cs_pass: str,
    cs_dir: str,
    cs_port: int = 50050,
    debug: bool = False,
) -> str:
    """
    Return the Robot Framework ``Library`` line(s) that import the
    cobaltstrike class with all constructor arguments pre-filled.

    The Robot Framework ``WITH NAME`` + named-arg syntax requires each arg
    on its own continuation line (``...``).  Example output::

        Library    cobaltstrikec2/cobaltstrike.py
        ...    WITH NAME    cs
        ...    local_bind_ip=10.10.104.30
        ...    user=operator
        ...    cs_password=P@ssw0rd
        ...    cs_dir=/opt/cobaltstrike
        ...    port=50050
        ...    debug=False

    Parameters
    ----------
    cs_ip:
        Teamserver IP (also used as local_bind_ip for the library).
    cs_user, cs_pass:
        Credentials for the agscript connection.
    cs_dir:
        Absolute path to the Cobalt Strike installation directory.
    cs_port:
        Teamserver port (default 50050).
    debug:
        Pass ``True`` to enable verbose debug output inside the library.
    """
    debug_str = "True" if debug else "False"
    lines = [
        f"Library    {_LIBRARY_PATH}",
        f"...    WITH NAME    {_LIBRARY_ALIAS}",
        f"...    local_bind_ip={cs_ip}",
        f"...    user={cs_user}",
        f"...    cs_password={cs_pass}",
        f"...    cs_dir={cs_dir}",
        f"...    port={cs_port}",
        f"...    debug={debug_str}",
    ]
    return "\n".join(lines)


def build_robot_header(
    cs_ip: str,
    cs_user: str,
    cs_pass: str,
    cs_dir: str,
    cs_port: int = 50050,
    debug: bool = False,
    suite_doc: str = "Generated by Lumen Campaign Studio",
    extra_libraries: Optional[List[str]] = None,
    resource_files: Optional[List[str]] = None,
    suite_setup: Optional[str] = None,
    suite_teardown: Optional[str] = None,
) -> str:
    """
    Build the complete ``*** Settings ***`` section for a generated .robot
    suite, with the cobaltstrike library properly initialised.

    Parameters
    ----------
    extra_libraries:
        Additional Library lines to append (e.g. ``["SSHLibrary", "SCPLibrary"]``).
    resource_files:
        Resource import lines (e.g. ``["hunt_1.resource"]``).
    suite_setup / suite_teardown:
        Optional keyword names for Suite Setup / Suite Teardown.
    """
    lib_decl = build_library_declaration(
        cs_ip=cs_ip,
        cs_user=cs_user,
        cs_pass=cs_pass,
        cs_dir=cs_dir,
        cs_port=cs_port,
        debug=debug,
    )

    lines = [
        "*** Settings ***",
        f"Documentation    {suite_doc}",
        lib_decl,
    ]

    for lib in (extra_libraries or []):
        lines.append(f"Library    {lib}")

    for res in (resource_files or []):
        lines.append(f"Resource    {res}")

    if suite_setup:
        lines.append(f"Suite Setup    {suite_setup}")
    if suite_teardown:
        lines.append(f"Suite Teardown    {suite_teardown}")

    return "\n".join(lines)


def build_variables_section(settings: Dict[str, str]) -> str:
    """
    Build a ``*** Variables ***`` section from a flat dict of name→value pairs.

    All names are uppercased and wrapped in ``${}`` if not already.
    Values that look like booleans are kept as-is (``True`` / ``False``).

    Example::

        build_variables_section({
            "TARGET1":     "172.16.2.5",
            "CS_PORT":     "50050",
            "DEBUG_MODE":  "False",
        })

    produces::

        *** Variables ***
        ${TARGET1}         172.16.2.5
        ${CS_PORT}         50050
        ${DEBUG_MODE}      False
    """
    lines = ["*** Variables ***"]
    for raw_name, value in settings.items():
        name = raw_name.upper()
        if not name.startswith("${"):
            name = f"${{{name}}}"
        lines.append(f"{name:<30}{value}")
    return "\n".join(lines)


def inject_cs_settings(
    robot_script: str,
    cs_ip: str,
    cs_user: str,
    cs_pass: str,
    cs_dir: str,
    cs_port: int = 50050,
    debug: bool = False,
) -> str:
    """
    Given a .robot script that was generated WITHOUT a CS Library declaration
    (or with a bare ``Library    cobaltstrikec2/cobaltstrike.py`` line), replace
    that line with the full constructor-arg version.

    This is a safety net for scripts that pre-date this fix.  New scripts
    should use ``build_robot_header()`` from the start.

    The replacement is idempotent: if the full WITH NAME block is already
    present, the script is returned unchanged.
    """
    full_decl = build_library_declaration(
        cs_ip=cs_ip, cs_user=cs_user, cs_pass=cs_pass,
        cs_dir=cs_dir, cs_port=cs_port, debug=debug,
    )

    # Already has WITH NAME → nothing to do
    if f"WITH NAME    {_LIBRARY_ALIAS}" in robot_script:
        return robot_script

    # Replace bare library import
    bare_import = f"Library    {_LIBRARY_PATH}"
    if bare_import in robot_script:
        return robot_script.replace(bare_import, full_decl, 1)

    # No CS library import at all — insert after *** Settings *** line
    if "*** Settings ***" in robot_script:
        return robot_script.replace(
            "*** Settings ***",
            f"*** Settings ***\n{full_decl}",
            1,
        )

    # Last resort: prepend a Settings section
    return f"*** Settings ***\n{full_decl}\n\n{robot_script}"
