# server/test_integration.py
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

print("=" * 60)
print("LUMEN INTEGRATION CHECK")
print("=" * 60)

# ── Test 1: robot_script_builder imports and runs ─────────────
print("\n[1] robot_script_builder...")
try:
    from robot_script_builder import inject_cs_settings, build_library_declaration
    
    decl = build_library_declaration(
        cs_ip="10.10.104.30",
        cs_user="bah",
        cs_pass="P@ssw0rd",
        cs_dir="/opt/cobaltstrike",
        cs_port=50050,
    )
    print("    build_library_declaration: OK")
    assert "WITH NAME" in decl
    assert "10.10.104.30" in decl
    assert "P@ssw0rd" in decl
    
    # Test injection into a bare script
    bare = "*** Settings ***\nLibrary    cobaltstrikec2/cobaltstrike.py\n\n*** Test Cases ***\nDummy\n    Log    hi\n"
    injected = inject_cs_settings(bare, "10.10.104.30", "bah", "P@ssw0rd", "/opt/cobaltstrike")
    assert "WITH NAME" in injected, "Injection failed — WITH NAME not found"
    assert "10.10.104.30" in injected
    print("    inject_cs_settings: OK")
    
    # Idempotency check — running twice shouldn't double-inject
    injected2 = inject_cs_settings(injected, "10.10.104.30", "bah", "P@ssw0rd", "/opt/cobaltstrike")
    assert injected == injected2, "Injection is not idempotent!"
    print("    idempotency check: OK")
    print("  PASS")
except Exception as e:
    print(f"  FAIL: {e}")
    import traceback; traceback.print_exc()

# ── Test 2: cobaltstrike_module imports ───────────────────────
print("\n[2] cobaltstrike_module...")
try:
    from cobaltstrike_module import (
        start_c2, stop_c2, is_connected, get_teamserver_info,
        create_listener, list_listeners,
        create_payload, list_payloads,
        get_status, reset,
    )
    print("    all exports importable: OK")
    
    # Should be disconnected at startup
    assert not is_connected(), "Should not be connected before start_c2()"
    print("    is_connected() == False before start: OK")
    
    status = get_status()
    assert status["connected"] == False
    assert status["listeners"] == 0
    assert status["payloads"] == 0
    print("    get_status() shape: OK")
    
    # reset() is safe to call even when not connected
    reset()
    print("    reset() safe no-op: OK")
    
    # _require_connected raises correctly
    try:
        create_listener("test", 80)
        print("  FAIL: should have raised RuntimeError")
    except RuntimeError as e:
        print(f"    _require_connected raises RuntimeError: OK")
    
    print("  PASS")
except Exception as e:
    print(f"  FAIL: {e}")
    import traceback; traceback.print_exc()

# ── Test 3: main.py can import both modules ───────────────────
print("\n[3] main.py import surface...")
try:
    # We can't run the full FastAPI app here, but we can verify
    # the import block that was previously broken works
    import importlib.util
    spec = importlib.util.spec_from_file_location("cobaltstrike_module", 
           os.path.join(os.path.dirname(__file__), "cobaltstrike_module.py"))
    mod = importlib.util.load_from_spec = spec  # just confirm it loads
    
    # Confirm the exact names main.py imports are present
    from cobaltstrike_module import get_status as get_c2_status, reset as reset_c2
    from robot_script_builder import inject_cs_settings
    print("    main.py import aliases: OK")
    print("  PASS")
except Exception as e:
    print(f"  FAIL: {e}")
    import traceback; traceback.print_exc()

# ── Test 4: script injection end-to-end ──────────────────────
print("\n[4] End-to-end script injection...")
try:
    from robot_script_builder import inject_cs_settings
    
    # Simulate what main.py does in create_terminal_session()
    CS_IP   = "10.10.104.30"
    CS_USER = "bah"
    CS_PASS = "P@ssw0rd"
    CS_DIR  = "/opt/cobaltstrike"
    
    # A realistic generated script (what robotScriptGenerator.ts produces)
    sample_script = """*** Settings ***
Documentation    Hunt 1 — generated by Lumen
Library    cobaltstrikec2/cobaltstrike.py
Library    SSHLibrary

*** Variables ***
${TARGET1}         172.16.2.5
${CS_PORT}         50050

*** Test Cases ***
Initial Access
    Issue Shell Cmd    ${CURRENT_SESSION}    whoami
"""
    
    result = inject_cs_settings(
        robot_script=sample_script,
        cs_ip=CS_IP,
        cs_user=CS_USER,
        cs_pass=CS_PASS,
        cs_dir=CS_DIR,
    )
    
    assert "WITH NAME    cs" in result
    assert f"local_bind_ip={CS_IP}" in result
    assert f"cs_password={CS_PASS}" in result
    assert f"cs_dir={CS_DIR}" in result
    assert "SSHLibrary" in result, "SSHLibrary should be preserved"
    assert "${TARGET1}" in result, "Variables section should be preserved"
    
    print("    Injected script preview:")
    for i, line in enumerate(result.split('\n')[:15]):
        print(f"      {i+1:>2} | {line}")
    print("    ...")
    print("  PASS")
except Exception as e:
    print(f"  FAIL: {e}")
    import traceback; traceback.print_exc()

# ── Test 5: cobaltstrikec2 package structure ──────────────────
print("\n[5] cobaltstrikec2 package structure...")
try:
    cs_dir = os.path.join(os.path.dirname(__file__), "cobaltstrikec2")
    
    required = [
        "cobaltstrikec2/__init__.py",
        "cobaltstrikec2/cobaltstrike.py",
        "cobaltstrikec2/C2Library.py",
        "cobaltstrikec2/sudopass.py",
        "cobaltstrikec2/payload_automation/__init__.py",
        "cobaltstrikec2/payload_automation/striker.py",
        "cobaltstrikec2/payload_automation/beacon.py",
        "cobaltstrikec2/sleep_python_bridge/__init__.py",
        "cobaltstrikec2/sleep_python_bridge/striker.py",
        "cobaltstrikec2/sleep_python_bridge/sleepy.py",
    ]
    
    all_ok = True
    for rel_path in required:
        full = os.path.join(os.path.dirname(__file__), rel_path)
        exists = os.path.exists(full)
        status = "OK" if exists else "MISSING"
        if not exists:
            all_ok = False
        print(f"    {'✓' if exists else '✗'} {rel_path}  [{status}]")
    
    if all_ok:
        print("  PASS")
    else:
        print("  FAIL — missing files above")
except Exception as e:
    print(f"  FAIL: {e}")

print("\n" + "=" * 60)
print("Done. Fix any FAILs before rebuilding.")
print("=" * 60)
