// Generated by ProtoGraph Pipeline Engine
// Generated: 2026-01-16T18:45:31.431135Z
// DO NOT EDIT - Regenerate from ProtoGraph UI

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

export const API_CONFIG = {
  BASE_URL: API_BASE_URL,
  ENDPOINTS: {
    OPERATOR_MODULES: '/api/plugins/operator/modules',
    OPERATOR_MODULE_DETAIL: (key: string) => `/api/plugins/operator/modules/${key}`,
    OPERATOR_CATEGORIES: '/api/plugins/operator/categories',
    OPERATOR_TACTICS: '/api/plugins/operator/tactics',
    OPERATOR_STATS: '/api/plugins/operator/stats',
    OPERATOR_VALIDATE: '/api/plugins/operator/validate',
  }
};

// Type declaration for Vite env variables
declare global {
  interface ImportMetaEnv {
    VITE_API_URL?: string;
  }
}


//////////////////////////////////////
////// ORIGINAL - DO NOT DELETE ///////
//////////////////////////////////////

// const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

// export const API_CONFIG = {
//   BASE_URL: API_BASE_URL,
//   ENDPOINTS: {
//     LIBRARY_MODULES: '/api/library-modules',
//     MODULE_DETAIL: (key: string) => `/api/library-modules/${key}`,
//     VALIDATE_REQUIREMENTS: '/api/library-modules/validate-requirements',
//     CATEGORIES: '/api/library-modules/categories',
//     TACTICS: '/api/library-modules/tactics',
//     STATS: '/api/library-modules/stats',
//     // Search endpoints
//     SMART_SEARCH: '/api/search/smart',
//     ADVANCED_SEARCH: '/api/search/advanced',
//     // Module generation (Phase 2)
//     GENERATE_MODULE: '/api/library-modules/generate',
//   }
// };

// // Type declaration for Vite env variables
// declare global {
//   interface ImportMetaEnv {
//     VITE_API_URL?: string;
//   }
// }

